/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/auth/login": {
    /** User login */
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
          };
        };
      };
      responses: {
        /** @description Successful login */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              token?: string;
              expiresIn?: string;
              user?: {
                id?: number;
                email?: string;
                role?: string;
                name?: string;
                institutionId?: number;
              };
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              message?: string;
            };
          };
        };
      };
    };
  };
  "/auth/logout": {
    /** User logout */
    post: {
      responses: {
        /** @description Successful logout */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              message?: string;
            };
          };
        };
      };
    };
  };
  "/auth/request-password-reset": {
    /** Request password reset */
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
          };
        };
      };
      responses: {
        /** @description Recovery email sent */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              message?: string;
            };
          };
        };
        /** @description User not found */
        404: {
          content: {
            "application/json": {
              ok?: boolean;
              message?: string;
            };
          };
        };
      };
    };
  };
  "/auth/reset-password": {
    /** Reset password using token */
    post: {
      requestBody: {
        content: {
          "application/json": {
            token: string;
            /** Format: password */
            newPassword: string;
          };
        };
      };
      responses: {
        /** @description Password updated */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              message?: string;
            };
          };
        };
        /** @description Invalid token or missing fields */
        400: {
          content: never;
        };
      };
    };
  };
  "/institutions": {
    /** Get all institutions */
    get: {
      responses: {
        /** @description List of institutions */
        200: {
          content: {
            "application/json": components["schemas"]["Institution"][];
          };
        };
      };
    };
    /** Create an institution */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateInstitutionInput"];
        };
      };
      responses: {
        /** @description Created institution */
        201: {
          content: {
            "application/json": components["schemas"]["Institution"];
          };
        };
      };
    };
  };
  "/mail": {
    /** Send email */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["MailRequest"];
        };
      };
      responses: {
        /** @description Mail accepted for delivery */
        202: {
          content: {
            "application/json": {
              ok?: boolean;
              id?: string;
            };
          };
        };
      };
    };
  };
  "/users": {
    /** List users */
    get: {
      parameters: {
        query?: {
          /** @description Filter by user role */
          role?: "admin" | "coordinator" | "tutor" | "parent";
          /** @description Filter by institution id */
          institutionId?: number;
          /** @description Case-insensitive search in name or email */
          nameOrEmail?: string;
          /** @description Page number (1-based) */
          page?: number;
          /** @description Items per page */
          pageSize?: number;
        };
      };
      responses: {
        /** @description List of users */
        200: {
          content: {
            "application/json": components["schemas"]["UserWithInstitution"][];
          };
        };
      };
    };
    /** Create a user */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateUserWithBankAccountInput"];
        };
      };
      responses: {
        /** @description Created user */
        201: {
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
      };
    };
  };
  "/users/{id}": {
    /** Get a user by ID */
    get: {
      parameters: {
        path: {
          /** @description User ID */
          id: string;
        };
      };
      responses: {
        /** @description User found */
        200: {
          content: {
            "application/json": components["schemas"]["UserDetail"];
          };
        };
        /** @description User not found */
        404: {
          content: never;
        };
      };
    };
    /** Delete a user by ID */
    delete: {
      parameters: {
        path: {
          /** @description User ID */
          id: string;
        };
      };
      responses: {
        /** @description User deleted successfully */
        204: {
          content: never;
        };
      };
    };
  };
  "/users/{id}/bank-account": {
    /** Edit a user's bank account information */
    patch: {
      parameters: {
        path: {
          /** @description User ID */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UserBankAccountInput"];
        };
      };
      responses: {
        /** @description Updated bank account information */
        200: {
          content: {
            "application/json": components["schemas"]["UserBankAccount"];
          };
        };
        /** @description User not found */
        404: {
          content: never;
        };
      };
    };
  };
  "/users/{id}/personal-information": {
    /** Edit a user's personal information */
    patch: {
      parameters: {
        path: {
          /** @description User ID */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["EditUserPersonalInformationInput"];
        };
      };
      responses: {
        /** @description Updated user information */
        201: {
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
        /** @description User not found */
        404: {
          content: never;
        };
      };
    };
  };
  "/users/{id}/change-password": {
    /** Change a user's password */
    patch: {
      parameters: {
        path: {
          /** @description User ID */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ChangePasswordRequest"];
        };
      };
      responses: {
        /** @description Password updated successfully */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              message?: string;
            };
          };
        };
        /** @description Current password is incorrect */
        401: {
          content: never;
        };
        /** @description User not found */
        404: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    UserLoginRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    UserLoginResponse: {
      ok: boolean;
      user: {
        id?: number;
        email?: string;
        role?: string;
        name?: string;
        institutionId?: number | null;
      };
    };
    MailRequest: {
      to: string | string[];
      cc?: string | string[];
      bcc?: string | string[];
      subject: string;
      text?: string;
      html?: string;
      /** Format: email */
      replyTo?: string;
    };
    User: {
      id: number;
      name: string;
      /** Format: email */
      email: string;
      /** @enum {string} */
      role: "admin" | "coordinator" | "tutor" | "guardian";
      rut?: string | null;
      phone?: string | null;
      address?: string | null;
      chargeEmail?: string | null;
      institutionId?: number | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    UserInput: {
      name: string;
      /** Format: email */
      email: string;
      /** @enum {string} */
      role: "admin" | "coordinator" | "tutor" | "guardian";
      rut?: string | null;
      phone?: string | null;
      address?: string | null;
      chargeEmail?: string | null;
      institutionId?: number | null;
    };
    Institution: {
      id: number;
      name: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CreateInstitutionInput: {
      name: string;
    };
    UserWithInstitution: components["schemas"]["User"] & {
      Institution?: components["schemas"]["Institution"];
    };
    UserBankAccount: {
      id?: number;
      userId?: number;
      bankName?: string;
      /** @enum {string} */
      accountType?: "AHORRO" | "CORRIENTE" | "VISTA";
      accountNumber?: string;
      /** Format: email */
      accountEmail?: string;
      accountName?: string;
      rut?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    Student: {
      id?: number;
      name?: string;
      guardianId?: number;
      institutionId?: number;
    };
    GuardianTutor: {
      guardianId?: number;
      tutorId?: number;
      institutionId?: number;
      active?: boolean;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    UserDetail: components["schemas"]["User"] & ({
      Institution?: components["schemas"]["Institution"];
      BankAccount?: components["schemas"]["UserBankAccount"];
      Students?: components["schemas"]["Student"][];
      TutorLinks?: (components["schemas"]["GuardianTutor"] & {
          Guardian?: components["schemas"]["User"];
        })[];
      GuardianLinks?: (components["schemas"]["GuardianTutor"] & {
          Tutor?: components["schemas"]["User"];
        })[];
    });
    UserBankAccountInput: {
      bankName: string;
      accountType: string;
      accountNumber: string;
      rut: string;
      /** Format: email */
      accountEmail: string;
      accountName: string;
    };
    CreateUserWithBankAccountInput: components["schemas"]["UserInput"] & ({
      BankAccount?: components["schemas"]["UserBankAccountInput"] | null;
    });
    UserByIdResponse: {
      ok?: boolean;
      user?: components["schemas"]["UserWithInstitution"];
    };
    EditUserPersonalInformationInput: {
      name: string;
      rut: string | null;
      phone: string | null;
      chargeEmail?: string | null;
      address?: string | null;
    };
    ChangePasswordRequest: {
      currentPassword: string;
      newPassword: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
