/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


/** OneOf type helpers */
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };
type XOR<T, U> = (T | U) extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U;
type OneOf<T extends any[]> = T extends [infer Only] ? Only : T extends [infer A, infer B, ...infer Rest] ? OneOf<[XOR<A, B>, ...Rest]> : never;

export interface paths {
  "/auth/login": {
    /** User login */
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
          };
        };
      };
      responses: {
        /** @description Successful login */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              token?: string;
              expiresIn?: string;
              user?: {
                id?: number;
                email?: string;
                role?: string;
                name?: string;
                institutionId?: number;
              };
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              message?: string;
            };
          };
        };
      };
    };
  };
  "/auth/logout": {
    /** User logout */
    post: {
      responses: {
        /** @description Successful logout */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              message?: string;
            };
          };
        };
      };
    };
  };
  "/auth/request-password-reset": {
    /** Request password reset */
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
          };
        };
      };
      responses: {
        /** @description Recovery email sent */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              message?: string;
            };
          };
        };
        /** @description User not found */
        404: {
          content: {
            "application/json": {
              ok?: boolean;
              message?: string;
            };
          };
        };
      };
    };
  };
  "/auth/reset-password": {
    /** Reset password using token */
    post: {
      requestBody: {
        content: {
          "application/json": {
            token: string;
            /** Format: password */
            newPassword: string;
          };
        };
      };
      responses: {
        /** @description Password updated */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              message?: string;
            };
          };
        };
        /** @description Invalid token or missing fields */
        400: {
          content: never;
        };
      };
    };
  };
  "/classes": {
    /**
     * List classes with details
     * @description Returns classes with related information (ClassPayment, Tutor, Student + Guardian, Institution).
     *
     * Scoping depends on the authenticated role:
     * - guardian: only classes for the guardian's students (and institution)
     * - tutor: only classes for the tutor (and institution)
     * - coordinator: all classes in the coordinator's institution
     * - admin: requires institutionId query param
     */
    get: {
      parameters: {
        query?: {
          /** @description Filter by class date >= startDate */
          startDate?: string;
          /** @description Filter by class date <= endDate */
          endDate?: string;
          /** @description Optional filter by tutorId (ignored for role tutor) */
          tutorId?: number;
          /** @description Optional filter by guardianId (ignored for role guardian) */
          guardianId?: number;
          /** @description Optional filter by studentId */
          studentId?: number;
          /** @description Required for role admin (institution to query) */
          institutionId?: number;
          /** @description Page number (1-based). If provided with pageSize, enables pagination. */
          page?: number;
          /** @description Items per page. If provided with page, enables pagination. */
          pageSize?: number;
        };
      };
      responses: {
        /** @description Array of class details */
        200: {
          content: {
            "application/json": components["schemas"]["ClassDetails"][];
          };
        };
        /** @description Forbidden */
        403: {
          content: never;
        };
      };
    };
    /**
     * Create a class
     * @description Creates a class and its related ClassPayment.
     *
     * This endpoint can be used by 3 roles:
     * - tutor: institutionId and tutorId are inferred from the authenticated tutor.
     * - coordinator: institutionId is inferred from the authenticated coordinator; tutorId must be provided.
     * - admin: tutorId and institutionId must be provided.
     */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateClassInput"];
        };
      };
      responses: {
        /** @description Created class and its payment */
        201: {
          content: {
            "application/json": components["schemas"]["CreateClassResponse"];
          };
        };
        /** @description Forbidden (role not allowed) */
        403: {
          content: never;
        };
      };
    };
  };
  "/classes/cash-flow-summary": {
    /**
     * Get classes cash flow summary
     * @description Returns a cash-flow summary computed from ClassPayment.
     *
     * The returned shape depends on the authenticated role:
     * - guardian/tutor: { pendingAmount, paidAmount }
     * - coordinator/admin: { pendingIncomes, receivedIncomes, pendingExpenses, paidExpenses }
     *
     * Notes about scoping:
     * - guardian: scoped to the authenticated guardian (and institution)
     * - tutor: scoped to the authenticated tutor (and institution)
     * - coordinator: scoped to the authenticated coordinator's institution
     * - admin: requires institutionId query param
     */
    get: {
      parameters: {
        query?: {
          /** @description Filter by class date >= startDate */
          startDate?: string;
          /** @description Filter by class date <= endDate */
          endDate?: string;
          /** @description Optional filter by tutorId (ignored for role tutor) */
          tutorId?: number;
          /** @description Optional filter by guardianId (ignored for role guardian) */
          guardianId?: number;
          /** @description Optional filter by studentId */
          studentId?: number;
          /** @description Required for role admin (institution to query) */
          institutionId?: number;
        };
      };
      responses: {
        /** @description Cash flow summary */
        200: {
          content: {
            "application/json": components["schemas"]["ClassesCashFlowSummaryResponse"];
          };
        };
        /** @description Forbidden */
        403: {
          content: never;
        };
      };
    };
  };
  "/classes/{classId}": {
    /**
     * Delete a class
     * @description Deletes the class and any related ClassPayment.
     */
    delete: {
      parameters: {
        path: {
          classId: number;
        };
      };
      responses: {
        /** @description Deleted successfully */
        204: {
          content: never;
        };
        /** @description Forbidden */
        403: {
          content: never;
        };
      };
    };
  };
  "/classes/class-payments/{classPaymentId}/status": {
    /**
     * Update class payment status
     * @description Updates guardianPaymentStatus and/or tutorPaymentStatus for a ClassPayment.
     * Provide at least one of the two fields.
     */
    patch: {
      parameters: {
        path: {
          classPaymentId: number;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateClassPaymentStatusInput"];
        };
      };
      responses: {
        /** @description Updated ClassPayment */
        200: {
          content: {
            "application/json": components["schemas"]["ClassPayment"];
          };
        };
        /** @description Forbidden */
        403: {
          content: never;
        };
      };
    };
  };
  "/fees/{institutionId}": {
    /** Get all active fees from an institution */
    get: {
      parameters: {
        path: {
          /** @description Institution ID */
          institutionId: number;
        };
      };
      responses: {
        /** @description List of active fees */
        200: {
          content: {
            "application/json": components["schemas"]["Fee"][];
          };
        };
        /** @description Institution not found */
        404: {
          content: {
            "application/json": {
              ok?: boolean;
              message?: string;
            };
          };
        };
      };
    };
  };
  "/fees/edit": {
    /** Edit fees */
    put: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["EditFeesRequest"];
        };
      };
      responses: {
        /** @description Fees updated successfully */
        200: {
          content: {
            "application/json": components["schemas"]["EditFeesResponse"];
          };
        };
        /** @description Bad request - validation error */
        400: {
          content: {
            "application/json": {
              ok?: boolean;
              message?: string;
            };
          };
        };
        /** @description Forbidden - admin access required */
        403: {
          content: {
            "application/json": {
              ok?: boolean;
              message?: string;
            };
          };
        };
        /** @description One or more fees not found */
        404: {
          content: {
            "application/json": {
              ok?: boolean;
              message?: string;
            };
          };
        };
      };
    };
  };
  "/fees/simulate": {
    /** Simulate a fee payment given a custom duration */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["SimulateFeePaymentRequest"];
        };
      };
      responses: {
        /** @description Simulated fee payment */
        200: {
          content: {
            "application/json": components["schemas"]["SimulateFeePaymentResponse"];
          };
        };
        /** @description Bad request - fees list is required */
        400: {
          content: {
            "application/json": {
              ok?: boolean;
              message?: string;
            };
          };
        };
        /** @description Fee not found */
        404: {
          content: {
            "application/json": {
              ok?: boolean;
              message?: string;
            };
          };
        };
      };
    };
  };
  "/institutions": {
    /** Get all institutions */
    get: {
      parameters: {
        query?: {
          /** @description If false, only active institutions are returned. If true or omitted, returns all. */
          sendInactive?: boolean;
        };
      };
      responses: {
        /** @description List of institutions */
        200: {
          content: {
            "application/json": components["schemas"]["Institution"][];
          };
        };
      };
    };
    /**
     * Create an institution
     * @description Creates an institution and clones fee rows from institution id=1 (The Grange School).
     */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateInstitutionInput"];
        };
      };
      responses: {
        /** @description Created institution */
        201: {
          content: {
            "application/json": components["schemas"]["CreateInstitutionResponse"];
          };
        };
      };
    };
  };
  "/institutions/{institutionId}/guardians": {
    /** Get guardians from an institution */
    get: {
      parameters: {
        path: {
          /** @description Institution ID */
          institutionId: string;
        };
      };
      responses: {
        /** @description List of guardian */
        200: {
          content: never;
        };
      };
    };
  };
  "/institutions/search": {
    /** Search institutions by name */
    get: {
      parameters: {
        query: {
          /** @description Search query to match institution names */
          query: string;
        };
      };
      responses: {
        /** @description List of institutions matching the search query */
        200: {
          content: {
            "application/json": components["schemas"]["Institution"][];
          };
        };
        /** @description Bad request - search query is required */
        400: {
          content: {
            "application/json": {
              ok?: boolean;
              message?: string;
            };
          };
        };
        /** @description Forbidden - admin access required */
        403: {
          content: {
            "application/json": {
              ok?: boolean;
              message?: string;
            };
          };
        };
      };
    };
  };
  "/institutions/{id}": {
    /**
     * Delete (deactivate) an institution
     * @description Deletes an institution only if there are no pending class payments in the last 12 months and all coordinator payments for those months exist and are completed. Operation is a soft delete that deactivates the institution and its users.
     */
    delete: {
      parameters: {
        path: {
          /** @description Institution ID */
          id: number;
        };
      };
      responses: {
        /** @description Institution deleted */
        200: {
          content: {
            "application/json": components["schemas"]["DeleteInstitutionResponse"];
          };
        };
        /** @description Cannot delete due to pending or missing payments */
        400: {
          content: {
            "application/json": components["schemas"]["DeleteInstitutionResponse"];
          };
        };
      };
    };
  };
  "/institutions/{id}/reactivate": {
    /**
     * Reactivate an institution
     * @description Reactivates a previously deactivated institution.
     */
    patch: {
      parameters: {
        path: {
          /** @description Institution ID */
          id: number;
        };
      };
      responses: {
        /** @description Institution reactivated */
        200: {
          content: {
            "application/json": components["schemas"]["ReactivateInstitutionResponse"];
          };
        };
        /** @description Institution not found */
        404: {
          content: {
            "application/json": components["schemas"]["ReactivateInstitutionResponse"];
          };
        };
      };
    };
  };
  "/mail": {
    /** Send email */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["MailRequest"];
        };
      };
      responses: {
        /** @description Mail accepted for delivery */
        202: {
          content: {
            "application/json": {
              ok?: boolean;
              id?: string;
            };
          };
        };
      };
    };
  };
  "/students/{guardianId}": {
    /**
     * Get students by guardian ID
     * @description Retrieve students associated with a specific guardian.
     * - Admins/coordinators: returns all students
     * - Guardians/tutors: returns only active students
     */
    get: {
      parameters: {
        query?: {
          /** @description If false, only active students are returned for admin/coordinator. If true or omitted, returns all. Guardians/tutors always receive only active students. */
          sendInactive?: boolean;
        };
        path: {
          /** @description Guardian ID */
          guardianId: number;
        };
      };
      responses: {
        /** @description List of students retrieved successfully */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              students?: components["schemas"]["Student"][];
            };
          };
        };
        /** @description Forbidden - user is not authenticated */
        403: {
          content: never;
        };
        /** @description No students found for the specified guardian */
        404: {
          content: never;
        };
      };
    };
  };
  "/students/{id}/reactivate": {
    /**
     * Reactivate a student
     * @description Reactivates a previously deactivated student.
     * - Requires admin or coordinator role
     */
    patch: {
      parameters: {
        path: {
          /** @description Student ID */
          id: number;
        };
      };
      responses: {
        /** @description Student reactivated successfully */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              message?: string;
            };
          };
        };
        /** @description Invalid student id */
        400: {
          content: never;
        };
        /** @description Forbidden - user is not an admin or coordinator */
        403: {
          content: never;
        };
      };
    };
  };
  "/students/add": {
    /**
     * Add a student to a guardian
     * @description Create a student for a guardian or reactivate an existing inactive one with the same name (case-insensitive).
     * - Requires admin or coordinator role
     * - All fields are required
     * - If a student with the same name exists for the guardian and is inactive, it will be reactivated instead of creating a new record
     */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["AddStudentToGuardianRequest"];
        };
      };
      responses: {
        /** @description Student reactivated or already active */
        200: {
          content: {
            "application/json": components["schemas"]["AddStudentToGuardianResponse"];
          };
        };
        /** @description Student created and added to guardian successfully */
        201: {
          content: {
            "application/json": components["schemas"]["AddStudentToGuardianResponse"];
          };
        };
        /** @description Invalid input or validation error (missing required fields, institution not found) */
        400: {
          content: never;
        };
        /** @description Forbidden - user is not an admin or coordinator */
        403: {
          content: never;
        };
        /** @description Guardian not found */
        404: {
          content: never;
        };
      };
    };
  };
  "/students/delete": {
    /**
     * Remove a student from a guardian
     * @description Soft-delete (deactivate) a student by setting isActive = false for the specified guardian/student pair.
     * - Requires admin or coordinator role
     * - The student must be associated with the specified guardian
     */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["RemoveStudentFromGuardianRequest"];
        };
      };
      responses: {
        /** @description Student removed from guardian successfully */
        200: {
          content: {
            "application/json": components["schemas"]["RemoveStudentFromGuardianResponse"];
          };
        };
        /** @description Invalid input or validation error (missing required fields) */
        400: {
          content: never;
        };
        /** @description Forbidden - user is not an admin or coordinator */
        403: {
          content: never;
        };
        /** @description Student not found for the specified guardian */
        404: {
          content: never;
        };
      };
    };
  };
  "/users": {
    /** List users */
    get: {
      parameters: {
        query?: {
          /** @description Filter by user role */
          role?: "admin" | "coordinator" | "tutor" | "guardian";
          /** @description Filter by institution id */
          institutionId?: number;
          /** @description Case-insensitive search in name or email */
          nameOrEmail?: string;
          /** @description If false, only active users are returned. If true or omitted, returns all. */
          sendInactive?: boolean;
          /** @description Page number (1-based) */
          page?: number;
          /** @description Items per page */
          pageSize?: number;
        };
      };
      responses: {
        /** @description List of users */
        200: {
          content: {
            "application/json": components["schemas"]["UserWithInstitution"][];
          };
        };
      };
    };
    /**
     * Create a user
     * @description Create a new user in the system.
     * - Admins must provide the institution ID
     * - Coordinators automatically use their own institution
     * - Initial password is set to the RUT number without the verifying digit
     * - Email must be unique (database constraint)
     * - Phone, address, and chargeEmail are optional
     */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateUserWithBankAccountInput"];
        };
      };
      responses: {
        /** @description User created successfully */
        201: {
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
        /** @description Invalid input or validation error (missing required fields, invalid email format, or database constraint violation) */
        400: {
          content: never;
        };
        /** @description Forbidden - insufficient permissions */
        403: {
          content: never;
        };
      };
    };
  };
  "/users/{id}": {
    /**
     * Get a user by ID
     * @description Returns user details.
     * - For guardians/tutors, only active students are returned
     */
    get: {
      parameters: {
        path: {
          /** @description User ID */
          id: string;
        };
      };
      responses: {
        /** @description User found */
        200: {
          content: {
            "application/json": components["schemas"]["UserByIdResponse"];
          };
        };
        /** @description User not found */
        404: {
          content: never;
        };
      };
    };
    /**
     * Delete a user by ID
     * @description Soft delete a user by marking them as inactive (isActive = false).
     * - Admins and coordinators can delete users
     * - Coordinators cannot delete admin or coordinator users
     */
    delete: {
      parameters: {
        path: {
          /** @description User ID */
          id: string;
        };
      };
      responses: {
        /** @description User deleted successfully (soft delete) */
        204: {
          content: never;
        };
        /** @description Forbidden - user lacks permission to delete this user */
        403: {
          content: never;
        };
        /** @description User not found */
        404: {
          content: never;
        };
      };
    };
  };
  "/users/{id}/bank-account": {
    /** Edit a user's bank account information */
    patch: {
      parameters: {
        path: {
          /** @description User ID */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UserBankAccountInput"];
        };
      };
      responses: {
        /** @description Updated bank account information */
        200: {
          content: {
            "application/json": components["schemas"]["UserBankAccount"];
          };
        };
        /** @description User not found */
        404: {
          content: never;
        };
      };
    };
  };
  "/users/{id}/personal-information": {
    /** Edit a user's personal information */
    patch: {
      parameters: {
        path: {
          /** @description User ID */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["EditUserPersonalInformationInput"];
        };
      };
      responses: {
        /** @description Updated user information */
        201: {
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
        /** @description User not found */
        404: {
          content: never;
        };
      };
    };
  };
  "/users/{id}/change-password": {
    /** Change a user's password */
    patch: {
      parameters: {
        path: {
          /** @description User ID */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ChangePasswordRequest"];
        };
      };
      responses: {
        /** @description Password updated successfully */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              message?: string;
            };
          };
        };
        /** @description Current password is incorrect */
        401: {
          content: never;
        };
        /** @description User not found */
        404: {
          content: never;
        };
      };
    };
  };
  "/users/{id}/tutor-links": {
    /** Get tutor links for a user */
    get: {
      parameters: {
        path: {
          /** @description User ID */
          id: string;
        };
      };
      responses: {
        /** @description Tutor links retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["TutorLink"][];
          };
        };
        /** @description User not found */
        404: {
          content: never;
        };
      };
    };
  };
  "/users/{id}/guardian-links": {
    /** Get guardian links for a user */
    get: {
      parameters: {
        path: {
          /** @description User ID */
          id: string;
        };
      };
      responses: {
        /** @description Guardian links retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["GuardianLink"][];
          };
        };
        /** @description User not found */
        404: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    UserLoginRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    UserLoginResponse: {
      ok: boolean;
      user: {
        id?: number;
        email?: string;
        role?: string;
        name?: string;
        institutionId?: number | null;
      };
    };
    MailRequest: {
      to: string | string[];
      cc?: string | string[];
      bcc?: string | string[];
      subject: string;
      text?: string;
      html?: string;
      /** Format: email */
      replyTo?: string;
    };
    User: {
      id: number;
      name: string;
      /** Format: email */
      email: string;
      /** @enum {string} */
      role: "admin" | "coordinator" | "tutor" | "guardian";
      rut?: string | null;
      phone?: string | null;
      address?: string | null;
      chargeEmail?: string | null;
      institutionId?: number | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    UserInput: {
      /** @description User full name (required) */
      name: string;
      /**
       * Format: email
       * @description User email (must be unique, required)
       */
      email: string;
      /**
       * @description User role (required)
       * @enum {string}
       */
      role: "admin" | "coordinator" | "tutor" | "guardian";
      /** @description RUT in format XX.XXX.XXX-K (required, used to generate initial password) */
      rut: string;
      /** @description Phone number (optional) */
      phone?: string | null;
      /** @description Address (optional) */
      address?: string | null;
      /**
       * Format: email
       * @description Charge email (optional)
       */
      chargeEmail?: string | null;
      /** @description Institution ID (required for non-admin users, inferred for coordinators) */
      institutionId?: number | null;
    };
    Institution: {
      id: number;
      name: string;
      isActive: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CreateInstitutionInput: {
      name: string;
    };
    CreateInstitutionResponse: {
      institution: components["schemas"]["Institution"];
      fees: components["schemas"]["Fee"][];
    };
    DeleteInstitutionResponse: {
      ok: boolean;
      message: string;
    };
    ReactivateInstitutionResponse: {
      ok: boolean;
      message: string;
    };
    UserWithInstitution: components["schemas"]["User"] & {
      Institution?: components["schemas"]["Institution"];
    };
    UserBankAccount: {
      id?: number;
      userId?: number;
      bankName?: string;
      /** @enum {string} */
      accountType?: "AHORRO" | "CORRIENTE" | "VISTA";
      accountNumber?: string;
      /** Format: email */
      accountEmail?: string;
      accountName?: string;
      rut?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    Student: {
      id?: number;
      name?: string;
      guardianId?: number;
      institutionId?: number;
      isActive?: boolean;
    };
    StudentSummary: {
      id: number;
      name: string;
    };
    TutorSummary: {
      name: string;
    };
    GuardianLinkWithTutor: {
      tutorId: number;
      Tutor: components["schemas"]["TutorSummary"];
    };
    UserWithGuardianLinks: {
      id: number;
      name: string;
      Students: components["schemas"]["StudentSummary"][];
      GuardianLinks: components["schemas"]["GuardianLinkWithTutor"][];
    };
    GuardianTutor: {
      guardianId?: number;
      tutorId?: number;
      institutionId?: number;
      active?: boolean;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    TutorLink: components["schemas"]["GuardianTutor"] & {
      Guardian?: components["schemas"]["User"];
    };
    GuardianLink: components["schemas"]["GuardianTutor"] & {
      Tutor?: components["schemas"]["User"];
    };
    UserDetail: components["schemas"]["User"] & ({
      Institution?: components["schemas"]["Institution"];
      BankAccount?: components["schemas"]["UserBankAccount"];
      Students?: components["schemas"]["Student"][];
      TutorLinks?: (components["schemas"]["GuardianTutor"] & {
          Guardian?: components["schemas"]["User"];
        })[];
      GuardianLinks?: (components["schemas"]["GuardianTutor"] & {
          Tutor?: components["schemas"]["User"];
        })[];
    });
    UserBankAccountInput: {
      userId?: number;
      bankName: string;
      accountType: string;
      accountNumber: string;
      rut: string;
      /** Format: email */
      accountEmail: string;
      accountName: string;
    };
    /** @enum {string} */
    ClassSubject: "biology" | "chemistry" | "physics" | "mathematics" | "spanish" | "french" | "english" | "pet" | "socialStudies" | "studySkills" | "other";
    /** @enum {string} */
    ClassModality: "inPerson" | "online";
    /** @enum {string} */
    ClassType: "school" | "university" | "cancelled";
    /** @enum {string} */
    PaymentStatus: "completed" | "pending";
    /** @enum {string} */
    PaymentType: "card" | "bankTransfer";
    Class: {
      id: number;
      /** Format: date-time */
      date: string;
      subject: components["schemas"]["ClassSubject"];
      modality: components["schemas"]["ClassModality"];
      numberOfStudents: number;
      type: components["schemas"]["ClassType"];
      duration: number;
      institutionId: number;
      studentId: number;
      tutorId: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    ClassPayment: {
      id: number;
      classId: number;
      guardianAmount: number;
      guardianPaymentStatus: components["schemas"]["PaymentStatus"];
      guardianPaymentType: components["schemas"]["PaymentType"];
      tutorAmount: number;
      tutorPaymentStatus: components["schemas"]["PaymentStatus"];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CreateClassBaseInput: {
      studentId: number;
      /**
       * @description ISO 8601 date-time string
       * @example 2025-12-31T10:00:00.000Z
       */
      date: string;
      numberOfStudents: number;
      /** @description Duration in minutes */
      duration: number;
      subject: components["schemas"]["ClassSubject"];
      type: components["schemas"]["ClassType"];
      modality: components["schemas"]["ClassModality"];
    };
    /** @description Tutor creates a class. institutionId and tutorId are inferred from the authenticated tutor. */
    CreateClassAsTutorInput: components["schemas"]["CreateClassBaseInput"];
    /** @description Coordinator creates a class. institutionId is inferred from the authenticated coordinator; tutorId must be provided. */
    CreateClassAsCoordinatorInput: components["schemas"]["CreateClassBaseInput"] & {
      /** @description Tutor who will teach the class */
      tutorId: number;
    };
    /** @description Admin creates a class. tutorId and institutionId must be provided. */
    CreateClassAsAdminInput: components["schemas"]["CreateClassBaseInput"] & {
      /** @description Tutor who will teach the class */
      tutorId: number;
      /** @description Institution that owns the class */
      institutionId: number;
    };
    /** @description Role-based input. Required fields depend on authenticated user role (tutor/coordinator/admin). */
    CreateClassInput: components["schemas"]["CreateClassAsTutorInput"] | components["schemas"]["CreateClassAsCoordinatorInput"] | components["schemas"]["CreateClassAsAdminInput"];
    CreateClassResponse: {
      class: components["schemas"]["Class"];
      classPayment: components["schemas"]["ClassPayment"];
    };
    ClassesCashFlowSummaryAmounts: {
      /** @description Pending amount for the authenticated role */
      pendingAmount: number;
      /** @description Paid amount for the authenticated role */
      paidAmount: number;
    };
    ClassesCashFlowSummaryInstitution: {
      /** @description Pending guardian incomes (institution scope) */
      pendingIncomes: number;
      /** @description Received guardian incomes (institution scope) */
      receivedIncomes: number;
      /** @description Pending tutor expenses (institution scope) */
      pendingExpenses: number;
      /** @description Paid tutor expenses (institution scope) */
      paidExpenses: number;
    };
    /** @description Cash-flow summary. Shape depends on authenticated role (guardian/tutor vs coordinator/admin). */
    ClassesCashFlowSummaryResponse: components["schemas"]["ClassesCashFlowSummaryAmounts"] | components["schemas"]["ClassesCashFlowSummaryInstitution"];
    UserIdName: {
      id: number;
      name: string;
    };
    StudentWithGuardianSummary: {
      id: number;
      name: string;
      Guardian: components["schemas"]["UserIdName"];
    };
    InstitutionSummary: {
      id: number;
      name: string;
    };
    /** @description Tutor basic info (id and name) */
    TutorBrief: components["schemas"]["UserIdName"];
    /** @description Class with included relations: ClassPayment, Tutor, Student (with Guardian), Institution. */
    ClassDetails: components["schemas"]["Class"] & {
      ClassPayment?: components["schemas"]["ClassPayment"];
      Tutor: components["schemas"]["TutorBrief"];
      Student: components["schemas"]["StudentWithGuardianSummary"];
      Institution: components["schemas"]["InstitutionSummary"];
    };
    /** @description Provide at least one of guardianPaymentStatus or tutorPaymentStatus. */
    UpdateClassPaymentStatusInput: OneOf<[{
      guardianPaymentStatus: components["schemas"]["PaymentStatus"];
    }, {
      tutorPaymentStatus: components["schemas"]["PaymentStatus"];
    }, {
      guardianPaymentStatus: components["schemas"]["PaymentStatus"];
      tutorPaymentStatus: components["schemas"]["PaymentStatus"];
    }]>;
    CreateUserWithBankAccountInput: components["schemas"]["UserInput"] & ({
      BankAccount?: components["schemas"]["UserBankAccountInput"] | null;
    });
    /** @description UserDetail with optional coordinatorProfitShare field. coordinatorProfitShare is only present when user role is coordinator. */
    UserByIdResponse: components["schemas"]["UserDetail"] & ({
      /** @description Profit share percentage for coordinator users. Only present when user role is coordinator. */
      coordinatorProfitShare?: number | null;
    });
    EditUserPersonalInformationInput: {
      name: string;
      rut: string | null;
      phone: string | null;
      chargeEmail?: string | null;
      address?: string | null;
    };
    ChangePasswordRequest: {
      currentPassword: string;
      newPassword: string;
    };
    Fee: {
      id: number;
      type: string;
      /** @enum {string} */
      modality: "inPerson" | "online" | "cancelled";
      numberOfStudents: number;
      guardianAmount: number;
      tutorAmount: number;
      institutionId: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    SimulateFeePaymentRequest: {
      fees: components["schemas"]["Fee"][];
      type: string;
      /** @enum {string} */
      classModality: "inPerson" | "online" | "cancelled";
      numberOfStudents: number;
      /** @description Duration in minutes */
      duration: number;
    };
    SimulateFeePaymentResponse: {
      ok: boolean;
      result: OneOf<[number, {
        guardianAmount: number;
        tutorAmount: number;
      }]>;
    };
    EditFeesRequest: {
      /** @description Array of fees to update. Can also be a single fee object for backward compatibility. */
      fees: {
          /** @description Fee ID to update */
          feeId: number;
          /** @description New tutor amount */
          tutorAmount: number;
          /** @description New guardian amount */
          guardianAmount: number;
        }[];
    };
    EditFeesResponse: {
      ok: boolean;
      message: string;
    };
    CreateGuardianInput: {
      /** @description Guardian name */
      name: string;
      /**
       * Format: email
       * @description Guardian email
       */
      email: string;
      /** @description Guardian RUT (e.g., 12345678-9) */
      rut: string;
      /** @description Guardian phone number (optional) */
      phone?: string | null;
      /** @description Guardian address (optional) */
      address?: string | null;
      /**
       * Format: email
       * @description Charge email (optional)
       */
      chargeEmail?: string | null;
      /** @description Institution ID (required for admin, inferred for coordinator) */
      institution?: number;
    };
    CreateGuardianResponse: {
      ok: boolean;
      guardian: components["schemas"]["User"];
    };
    AddStudentToGuardianRequest: {
      /** @description Student name (required) */
      name: string;
      /** @description Institution ID (required) */
      institutionId: number;
      /** @description Guardian ID (required) */
      guardianId: number;
    };
    AddStudentToGuardianResponse: {
      ok: boolean;
      student: components["schemas"]["Student"];
      /** @description True when an existing inactive student was reactivated instead of creating a new record */
      reactivated?: boolean;
    };
    RemoveStudentFromGuardianRequest: {
      /** @description Guardian ID (required) */
      guardianId: number;
      /** @description Student ID (required) */
      studentId: number;
    };
    RemoveStudentFromGuardianResponse: {
      ok: boolean;
      message: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
